// ------------------- DỮ LIỆU SẢN PHẨM PHỤ KIỆN -------------------

const phukienProducts = [
  {
    id: 1,
    name: "Ốp lưng IPhone 17 Pro Max ",
    img: "assets/images/phukien/oplung/oplung-iphone17pm.jpg",
    price: 500000,
    oldPrice: 550000,
    discount: 10,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 2,
    name: "Ốp lưng IPhone 16 Plus",
    img: "assets/images/phukien/oplung/oplung-iphone16plus.jpg",
    price: 620000,
    oldPrice: 690000,
    discount: 10,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 3,
    name: "Sạc nhanh Apple 35W",
    img: "assets/images/phukien/sac&cap/sac-35w.jpeg",
    price: 1290000,
    oldPrice: 1490000,
    discount: 13,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 4,
    name: "Cáp TypeC",
    img: "assets/images/phukien/sac&cap/cap-typec.jpg",
    price: 310000,
    oldPrice: 390000,
    discount: 10,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 5,
    name: "Sạc nhanh Apple 140W",
    img: "assets/images/phukien/sac&cap/sac-140w.jpg",
    price: 2390000,
    oldPrice: 2490000,
    discount: 20,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 6,
    name: "Kính cường lực iPhone 17 Pro Max",
    img: "assets/images/phukien/kinhcuongluc/kinh-cuong-luc-17pm.webp",
    price: 250000,
    oldPrice: 300000,
    discount: 25,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 7,
    name: "Kính cường lực iPhone 15 Pro Max",
    img: "assets/images/phukien/kinhcuongluc/kinh-cuong-luc-15pm.webp",
    price: 150000,
    oldPrice: 200000,
    discount: 25,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 8,
    name: "Sạc dự phòng Magsafe 10000mAh Apple",
    img: "assets/images/phukien/sac&cap/sac-du-phong-magsafe.png",
    price: 1890000,
    oldPrice: 2290000,
    discount: 17,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 9,
    name: "Tai nghe Có Dây Samsung IA500 ",
    img: "assets/images/phukien/tainghe/tai-nghe-1.jpg",
    price: 250000,
    oldPrice: 290000,
    discount: 15,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 10,
    name: "Tai nghe Có Dây Apple MMTN2",
    img: "assets/images/phukien/tainghe/tai-nghe-2.jpg",
    price: 540000,
    oldPrice: 690000,
    discount: 20,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 11,
    name: "Tai nghe Chụp Tai Gaming Asus TUF H3",
    img: "assets/images/phukien/tainghe/tai-nghe-3.jpg",
    price: 900000,
    oldPrice: 1000000,
    discount: 10,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 12,
    name: "Tai nghe chụp tai Sony MDR-ZX110A",
    img: "assets/images/phukien/tainghe/tai-nghe-4.jpg",
    price: 380000,
    oldPrice: 530000,
    discount: 28,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 13,
    name: "Tai nghe Có Dây Gaming Asus Rog Cetra II Core",
    img: "assets/images/phukien/tainghe/tai-nghe-5.jpg",
    price: 2390000,
    oldPrice: 2490000,
    discount: 20,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 14,
    name: "Tai nghe TWS Samsung Galaxy Buds3 Pro R630N",
    img: "assets/images/phukien/tainghe/tai-nghe-6.jpg",
    price: 3500000,
    oldPrice: 5300000,
    discount: 40,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 15,
    name: "Tai nghe Bluetooth Chụp Tai JBL Tune 520BT",
    img: "assets/images/phukien/tainghe/tai-nghe-7.jpg",
    price: 1000000,
    oldPrice: 1300000,
    discount: 25,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 16,
    name: "Tai nghe Bluetooth True Wireless Xiaomi Redmi Buds 6",
    img: "assets/images/phukien/tainghe/tai-nghe-8.jpg",
    price: 890000,
    oldPrice: 1500000,
    discount: 30,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 17,
    name: "Chuột Có dây Gaming Razer Basilisk V3 ",
    img: "assets/images/phukien/chuot&banphim/chuot-1.jpg",
    price: 950000,
    oldPrice: 1200000,
    discount: 20,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 18,
    name: "Chuột Bluetooth Logitech MX Master 4",
    img: "assets/images/phukien/chuot&banphim/chuot-2.jpg",
    price: 2900000,
    oldPrice: 3400000,
    discount: 14,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 19,
    name: "Chuột sạc Bluetooth Gaming Razer Basilisk V3 Pro 35K",
    img: "assets/images/phukien/chuot&banphim/chuot-3.jpg",
    price: 3900000,
    oldPrice: 4500000,
    discount: 14,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 20,
    name: "Chuột sạc Bluetooth Gaming Razer Cobra Pro",
    img: "assets/images/phukien/chuot&banphim/chuot-4.jpg",
    price: 2600000,
    oldPrice: 3200000,
    discount: 18,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 21,
    name: "Bàn Phím Cơ Bluetooth Akko TAC87 Horizon Mirror",
    img: "assets/images/phukien/chuot&banphim/banphim-1.jpg",
    price: 1250000,
    oldPrice: 1400000,
    discount: 20,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 22,
    name: "Bàn Phím Cơ Có Dây Gaming Razer BlackWidow V4 X Green Switc",
    img: "assets/images/phukien/chuot&banphim/banphim-2.jpg",
    price: 2500000,
    oldPrice: 3300000,
    discount: 25,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 23,
    name: "Bàn Phím Cơ Bluetooth Veekos Shine60 SP White Akko Flash Magnetic Switch",
    img: "assets/images/phukien/chuot&banphim/banphim-3.jpg",
    price: 1200000,
    oldPrice: 1300000,
    discount: 5,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
  {
    id: 24,
    name: "Bàn Phím Có Dây Gaming Asus TUF K1",
    img: "assets/images/phukien/chuot&banphim/banphim-4.jpeg",
    price: 890000,
    oldPrice: 990000,
    discount: 10,
    installment: "Trả góp 0%",
    shipping: "Miễn phí vận chuyển",
  },
];
